language: c

compiler:
  - gcc
  - clang

before_script:
  - autoreconf -vfi
  - sudo apt-get install -qq gengetopt
  - sudo apt-get install -qq libev-dev

env:
  - OPTIONS=""
  - OPTIONS="CPPFLAGS='-DDEBUG_FLAG'"

script: ./configure $OPTIONS && make clean all check distcheck || (cat test/test-suite.log && /bin/false)

## whitelist
branches:
  only:
    - master
    - next

notifications:
  email:
    - devel@fresse.org
