language: c

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -qq gengetopt
  - sudo apt-get install -qq libev-dev
  - sudo apt-get install -qq texinfo
  - sudo apt-get install -qq texlive

before_script:
  - autoreconf -vfi

env:
  - OPTIONS=""
  - OPTIONS="CPPFLAGS=-DDEBUG_FLAG"

script:
  - mkdir \=build
  - cd \=build
  - ../configure $OPTIONS
  - make clean all check distcheck

## whitelist
branches:
  only:
    - master
    - next

notifications:
  email:
    - devel@fresse.org
