language: c

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get -qq update

install:
  - sudo apt-get install -qq gengetopt
  - sudo apt-get install -qq libev-dev
  - sudo apt-get install -qq texinfo
  - sudo apt-get install -qq texlive

before_script:
  - ip -6 a
  - ip -6 ma
  - autoreconf -vfi

env:
  matrix:
    - OPTIONS=""

script:
  - mkdir \=build
  - cd \=build
  - ../configure $OPTIONS
  - make clean all check distcheck || (cat test/test-suite.log; test "0" = "1")

## whitelist
branches:
  only:
    - master
    - next

notifications:
  email:
    - devel@fresse.org
