language: c

compiler:
  - gcc
  - clang

before_script:
  - autoreconf -vfi
  - sudo apt-get install -qq gengetopt
  - sudo apt-get install -qq libev-dev

env:
  - OPTIONS=""
  - OPTIONS="CPPFLAGS='-DDEBUG_FLAG'"

script: 
  - ./configure $OPTIONS
  - make clean all check distcheck

after_failure:
  - cat test/test-suite.log

## whitelist
branches:
  only:
    - master
    - next

notifications:
  email:
    - devel@fresse.org
