language: c

compiler:
  - gcc
  - clang

before_script:
  - autoreconf -vfi
  - sudo apt-get install -qq gengetopt
  - sudo apt-get install -qq libev-dev
  - sudo apt-get install -qq texinfo
  - sudo apt-get install -qq texlive

env:
  - OPTIONS=""
  - OPTIONS="CPPFLAGS='-DDEBUG_FLAG'"

script:
  - mkdir \=build
  - cd \=build
  - ../configure $OPTIONS
  - make clean all check distcheck

after_failure:
  - cat test/test-suite.log

## whitelist
branches:
  only:
    - master
    - next

notifications:
  email:
    - devel@fresse.org
